workflows:
  ios:
    name: Build iOS App
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Run build
        script: |
          npx react-native run-ios --configuration Release
    artifacts:
      - *.ipa
    environment:
      XCODE_VERSION: "Xcode 13.3" # Choisis la version appropriée d'Xcode
