workflows:
  ios:
    name: Build iOS App
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build the app
        script: |
          npx react-native run-ios --configuration Release
    artifacts:
      - ios/build/Products/Release-iphoneos/*.ipa # Chemin vers le fichier .ipa
