version: 2.1

jobs:
  build-ios:
    macos:
      xcode: "13.4.1"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Install cocoapods
          command: pod install --project-directory=ios
      - run:
          name: Build IPA
          command: |
            xcodebuild \
              -workspace ios/KickStats.xcworkspace \
              -scheme KickStats \
              -configuration Release \
              -sdk iphoneos \
              -archivePath $PWD/build/KickStats.xcarchive archive

            xcodebuild \
              -exportArchive \
              -archivePath $PWD/build/KickStats.xcarchive \
              -exportOptionsPlist ios/exportOptions.plist \
              -exportPath $PWD/build

      - store_artifacts:
          path: build/KickStats.ipa
          destination: ios-app-ipa

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-ios
