version: 2.1

jobs:
  build-ios:
    macos:
      xcode: "14.0.0"  # Utilise une version d'Xcode disponible pour ton plan
    steps:
      - checkout
      - run:
          name: List project files
          command: ls -la
      - run:
          name: Install Cocoapods
          command: |
            cd ios
            pod install
      - run:
          name: Build IPA
          command: |
            xcodebuild \
              -workspace ios/KickStats.xcworkspace \
              -scheme KickStats \
              -configuration Release \
              -sdk iphoneos \
              -archivePath $PWD/build/KickStats.xcarchive archive

            xcodebuild \
              -exportArchive \
              -archivePath $PWD/build/KickStats.xcarchive \
              -exportOptionsPlist ios/exportOptions.plist \
              -exportPath $PWD/build

      - store_artifacts:
          path: build/KickStats.ipa
          destination: ios-app-ipa

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-ios
