version: 2.1

jobs:
  build-ios:
    macos:
      xcode: "13.4.1"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Install cocoapods
          command: pod install --project-directory=ios
      - run:
          name: Build IPA
          command: |
            xcodebuild \
              -workspace ios/KickStats.xcworkspace \
              -scheme KickStats \
              -configuration Release \
              -sdk iphoneos \
              -archivePath $PWD/build/KickStats.xcarchive archive

            xcodebuild \
              -exportArchive \
              -archivePath $PWD/build/KickStats.xcarchive \
              -exportOptionsPlist ios/exportOptions.plist \
              -exportPath $PWD/build

      - store_artifacts:
          path: build/KickStats.ipa
          destination: ios-app-ipa

  build-android:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Build APK
          command: |
            cd android
            ./gradlew assembleRelease
      - store_artifacts:
          path: android/app/build/outputs/apk/release/app-release.apk
          destination: android-app-apk

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-ios
      - build-android
